# Generated by Django 4.2.13 on 2026-06-18 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_notification_logs'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationTemplate',
            fields=[
                ('template_id', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True)),
                ('template_type', models.CharField(choices=[('First Notice', 'First Notice'), ('Second Notice', 'Second Notice'), ('Disconnection Warning', 'Disconnection Warning')], max_length=50)),
                ('channel', models.CharField(choices=[('Email', 'Email'), ('SMS', 'SMS')], max_length=20)),
                ('subject', models.CharField(blank=True, help_text='For Email only', max_length=255)),
                ('body', models.TextField(help_text='Use {customer_name}, {amount_due}, {days_overdue}, {plan}, {client_id}, {due_date}, {days_remaining} as placeholders')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['template_type', 'channel'],
                'unique_together': {('template_type', 'channel')},
            },
        ),
    ]
