# Generated by Django 4.2.13 on 2026-06-18 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_notificationtemplate'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailnotificationlog',
            name='is_new',
            field=models.BooleanField(default=True, help_text='Mark as False when admin views the notification'),
        ),
        migrations.AddField(
            model_name='smsnotificationlog',
            name='is_new',
            field=models.BooleanField(default=True, help_text='Mark as False when admin views the notification'),
        ),
    ]
