# Generated by Django 4.2.13 on 2026-06-18 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_emailnotificationlog_is_new_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('activity_id', models.AutoField(primary_key=True, serialize=False)),
                ('activity_type', models.CharField(choices=[('client_created', 'Client Created'), ('client_edited', 'Client Edited'), ('client_deleted', 'Client Deleted'), ('payment_recorded', 'Payment Recorded'), ('application_approved', 'Application Approved'), ('application_declined', 'Application Declined'), ('application_deleted', 'Application Deleted')], max_length=50)),
                ('entity_type', models.CharField(max_length=50)),
                ('entity_id', models.CharField(max_length=50)),
                ('entity_name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('old_value', models.TextField(blank=True, null=True)),
                ('new_value', models.TextField(blank=True, null=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('performed_by', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_new', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='api_activit_created_011954_idx'), models.Index(fields=['is_new'], name='api_activit_is_new_62857a_idx')],
            },
        ),
    ]
