# Generated by Django 4.2.13 on 2026-07-01 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_application_latitude_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitylog',
            name='activity_type',
            field=models.CharField(choices=[('client_created', 'Client Created'), ('client_edited', 'Client Edited'), ('client_deleted', 'Client Deleted'), ('payment_recorded', 'Payment Recorded'), ('application_submitted', 'Application Submitted'), ('application_approved', 'Application Approved'), ('application_declined', 'Application Declined'), ('application_deleted', 'Application Deleted'), ('ticket_created', 'Ticket Created'), ('ticket_updated', 'Ticket Updated'), ('ticket_resolved', 'Ticket Resolved'), ('ticket_closed', 'Ticket Closed')], max_length=50),
        ),
        migrations.AlterField(
            model_name='emailnotificationlog',
            name='notification_type',
            field=models.CharField(choices=[('Overdue Notice', 'Overdue Notice'), ('Final Warning', 'Final Warning'), ('Disconnection Notice', 'Disconnection Notice'), ('Payment Reminder', 'Payment Reminder'), ('Payment Receipt', 'Payment Receipt')], max_length=50),
        ),
        migrations.AlterField(
            model_name='notificationtemplate',
            name='template_type',
            field=models.CharField(choices=[('First Notice', 'First Notice'), ('Second Notice', 'Second Notice'), ('Disconnection Warning', 'Disconnection Warning'), ('Payment Receipt', 'Payment Receipt')], max_length=50),
        ),
        migrations.AlterField(
            model_name='smsnotificationlog',
            name='notification_type',
            field=models.CharField(choices=[('Overdue Notice', 'Overdue Notice'), ('Final Warning', 'Final Warning'), ('Disconnection Notice', 'Disconnection Notice'), ('Payment Reminder', 'Payment Reminder'), ('Payment Receipt', 'Payment Receipt')], max_length=50),
        ),
    ]
