# Generated by Django 4.2.13 on 2026-07-05 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_applicationdecision'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EmailNotificationLog',
        ),
        migrations.DeleteModel(
            name='SMSNotificationLog',
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='activity_type',
            field=models.CharField(choices=[('client_created', 'Client Created'), ('client_edited', 'Client Edited'), ('client_deleted', 'Client Deleted'), ('payment_recorded', 'Payment Recorded'), ('application_submitted', 'Application Submitted'), ('application_approved', 'Application Approved'), ('application_declined', 'Application Declined'), ('application_deleted', 'Application Deleted'), ('ticket_created', 'Ticket Created'), ('ticket_scheduled', 'Ticket Scheduled'), ('ticket_updated', 'Ticket Updated'), ('ticket_resolved', 'Ticket Resolved'), ('ticket_closed', 'Ticket Closed')], max_length=50),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Scheduled', 'Scheduled'), ('In Progress', 'In Progress'), ('Resolved', 'Resolved')], max_length=20),
        ),
    ]
