# Generated by Django 4.2.13 on 2026-07-06 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_delete_emailnotificationlog_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='overduenotification',
            name='hide_from_notifications',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='payment',
            name='hide_from_notifications',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='payment',
            name='notification_read',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ticket',
            name='hide_from_notifications',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ticket',
            name='notification_read',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='notificationtemplate',
            name='body',
            field=models.TextField(help_text='Use {customer_name}, {amount_due}, {days_overdue}, {plan}, {client_id}, {due_date}, {days_remaining}, {ticket_id}, {date}, {time}, {issue}, {address} as placeholders'),
        ),
        migrations.AlterField(
            model_name='notificationtemplate',
            name='template_type',
            field=models.CharField(choices=[('First Notice', 'First Notice'), ('Second Notice', 'Second Notice'), ('Disconnection Warning', 'Disconnection Warning'), ('Service Scheduled', 'Service Scheduled'), ('Service Rescheduled', 'Service Rescheduled'), ('Payment Receipt', 'Payment Receipt')], max_length=50),
        ),
    ]
