# Generated by Django 4.2.13 on 2026-06-23 16:39
# Fixed to allow multiple biometric types per user

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0004_allow_multiple_biometrics_and_nonunique_hash'),
    ]

    operations = [
        # Change OneToOneField to ForeignKey to allow multiple biometric records per user
        migrations.AlterField(
            model_name='biometricdata',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='biometric_data', to=settings.AUTH_USER_MODEL),
        ),
        # Update biometric type choices to include mobile_passkey
        migrations.AlterField(
            model_name='biometricdata',
            name='biometric_type',
            field=models.CharField(choices=[('facial', 'Facial Recognition'), ('fingerprint', 'Fingerprint'), ('mobile_passkey', 'Mobile Passkey')], max_length=20),
        ),
        # Update MFA method choices
        migrations.AlterField(
            model_name='mfasettings',
            name='method',
            field=models.CharField(choices=[('password_otp', 'Password + OTP'), ('password_facial', 'Password + Facial Recognition'), ('password_fingerprint', 'Password + Fingerprint'), ('password_otp_facial', 'Password + OTP + Facial'), ('password_otp_fingerprint', 'Password + OTP + Fingerprint'), ('password_otp_facial_fingerprint', 'Password + OTP + Facial + Fingerprint')], default='password_otp', max_length=50),
        ),
    ]
