# Generated by Django 4.2.13 on 2026-06-25 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0008_biometricdata_sample_image_path'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='auditlog',
            new_name='security_au_user_id_6d8368_idx',
            old_name='auditlog_user_timestamp_idx',
        ),
        migrations.RenameIndex(
            model_name='auditlog',
            new_name='security_au_action__33a154_idx',
            old_name='auditlog_action_timestamp_idx',
        ),
        migrations.AddField(
            model_name='loginattempt',
            name='login_method',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='securitysettings',
            name='otp_expiry_minutes',
            field=models.IntegerField(default=5),
        ),
    ]
